微信卡券 ticket 获取及签名
wechatpy/wechatpy pull request #195
Opened 2017-02-19 12:30 UTC by Jay54520

签名的生成与微信的[调试工具](http://mp.weixin.qq.com/debug/cgi-bin/sandbox?t=cardsign])相同，但是我在前端使用 JSSDK 调用这些参数会报错，没有找到原因。
```javascript
wx.chooseCard({
    shopId: '', // 门店Id
    cardType: '', // 卡券类型
    cardId: '', // 卡券Id
    timestamp: 0, // 卡券签名时间戳
    nonceStr: '', // 卡券签名随机串
    signType: '', // 签名方式，默认'SHA1'
    cardSign: '', // 卡券签名
    success: function (res) {
        var cardList= res.cardList; // 用户选中的卡券列表信息
    }
});
```
并且，我认为 get_jsapi_signature 也应该返回一个带有所有参数的字典，而不是只返回一个签名

2017-02-19 12:44 UTC, messense requested changes

2017-02-19 12:44 UTC, messense commented on wechatpy/client/api/jsapi.py
> +        card_signature_dict['sign'] = hashlib.sha1(str_to_sign).hexdigest()
签名计算可以直接用 `WeChatSigner`：

```python
signer = WeChatSigner()
signer.add_data(*card_signature_dict.values())
card_signature_dict['sign'] = signer.signature
```

2017-02-19 12:44 UTC, messense commented on wechatpy/client/api/jsapi.py
> +    def get_jsapi_card_signature_dict(self, jsapi_card_ticket, card_type, **kwargs):
Rename: `get_jsapi_card_params`？

2017-02-19 12:44 UTC, messense commented on wechatpy/client/api/jsapi.py
> +        expires_at = self.session.get('jsapi_card_ticket_expires_at', 0)
这些 `key` 增加 `appid` 前缀？

2017-02-19 12:44 UTC, messense commented on wechatpy/client/api/jsapi.py
> +        return str(int(time.time()))
这个函数只用了一次，没有必要。

2017-02-19 12:51 UTC, Jay54520 commented on wechatpy/client/api/jsapi.py
> +    def get_jsapi_card_signature_dict(self, jsapi_card_ticket, card_type, **kwargs):
我返回的是包含 sign 的一个字典:
```python
            {'card_type': 'GROUPON', 'noncestr': 'Wm3WZYTPz0wzccnW',
             'api_ticket': 'sM4AOVdWfPE4DxkXGEs8VMCPGGVi4C3VM0P37wVUCFvkVAy_90u5h9nbSlYy3-Sl-HhTdfl2fzFy1AOcHKP7qg',
             'appid': '123456', 'timestamp': 1414587457, 'sign': 'c47b1fb500eb35d8f2f9b9375b4491089df953e2'},

```

2017-02-19 12:52 UTC, messense commented on wechatpy/client/api/jsapi.py
> +    def get_jsapi_card_signature_dict(self, jsapi_card_ticket, card_type, **kwargs):
这个字典不就是 card jsapi 的参数（params）么？

2017-02-19 12:53 UTC, Jay54520 commented on wechatpy/client/api/jsapi.py
> +    def get_jsapi_card_signature_dict(self, jsapi_card_ticket, card_type, **kwargs):
前端调用需要这些参数，而不只是一个 sign

2017-02-19 12:54 UTC, messense commented on wechatpy/client/api/jsapi.py
> +    def get_jsapi_card_signature_dict(self, jsapi_card_ticket, card_type, **kwargs):
对啊，所以这个 API 应该叫做：`get_jsapi_card_params`

2017-02-19 12:54 UTC, messense commented on wechatpy/client/api/jsapi.py
> +    def get_jsapi_card_signature_dict(self, jsapi_card_ticket, card_type, **kwargs):
`dict` 是 Python 中的概念。

2017-02-19 12:54 UTC, Jay54520 commented on wechatpy/client/api/jsapi.py
> +        card_signature_dict['sign'] = hashlib.sha1(str_to_sign).hexdigest()
我一开始使用了 `WeChatSigner `，但是会出错，不知道为什么 self._data 增加了 key 进去，我只传入了 dict.values()
`[b'jsapi_ticket=sM4AOVdWfPE4DxkXGEs8VMCPGGVi4C3VM0P37wVUCFvkVAy_90u5h9nbSlYy3-Sl-HhTdfl2fzFy1AOcHKP7qg', b'noncestr=Wm3WZYTPz0wzccnW', b'timestamp=1414587457', b'url=http://mp.weixin.qq.com?params=value']`

2017-02-19 12:55 UTC, messense commented on wechatpy/client/api/jsapi.py
> +        card_signature_dict['sign'] = hashlib.sha1(str_to_sign).hexdigest()
需要 unpack，`*dict.values()`

2017-02-19 12:56 UTC, Jay54520 commented on wechatpy/client/api/jsapi.py
> +    def get_jsapi_card_signature_dict(self, jsapi_card_ticket, card_type, **kwargs):
对 我改下

2017-02-19 12:58 UTC, messense commented on wechatpy/client/api/jsapi.py
> +    def get_jsapi_card_signature_params(self, jsapi_card_ticket, card_type, **kwargs):
我觉得 `params` 已经隐含了 `signature`，要更明确的话，可以是 `get_signed_jsapi_card_params`

2017-02-19 13:11 UTC, Jay54520 commented on wechatpy/client/api/jsapi.py
> +        card_signature_dict['sign'] = hashlib.sha1(str_to_sign).hexdigest()
我 unpack 了，`args = ('GROUPON', 'Wm3WZYTPz0wzccnW', 'sM4AOVdWfPE4DxkXGEs8VMCPGGVi4C3VM0P37wVUCFvkVAy_90u5h9nbSlYy3-Sl-HhTdfl2fzFy1AOcHKP7qg', '123456', 1414587457)`
但是签名对不上，可能是没有排序。然后我添加 print，还打印不出来，`OSError: [Errno 22] Invalid argument`
```python
    @property
    def signature(self):
        """Get data signature"""
        self._data.sort()
        print('signature')
        print(self._data)

```

2017-02-19 13:14 UTC, messense requested changes

2017-02-19 13:14 UTC, messense commented on wechatpy/client/api/jsapi.py
> +    def get_jsapi_card_params(self, jsapi_card_ticket, card_type, **kwargs):
`jsapi_card_ticket` 简化成 `ticket` 吧

2017-02-19 13:15 UTC, messense commented on wechatpy/client/api/jsapi.py
> +        card_signature_dict['sign'] = hashlib.sha1(str_to_sign).hexdigest()
那这里先这样。

2017-02-19 13:17 UTC, Jay54520 commented on wechatpy/client/api/jsapi.py
> +    def get_jsapi_card_params(self, jsapi_card_ticket, card_type, **kwargs):
我认为不用。函数名叫 `get_jsapi_card_ticket` 里面，变量写成 `jsapi_card_ticket ` 没问题吧

2017-02-19 13:18 UTC, messense commented on wechatpy/client/api/jsapi.py
> +    def get_jsapi_card_params(self, jsapi_card_ticket, card_type, **kwargs):
函数名已经隐含了这里的 ticket 的来源

2017-02-19 13:19 UTC, messense commented on wechatpy/client/api/jsapi.py
> +    def get_jsapi_card_params(self, jsapi_card_ticket, card_type, **kwargs):
这里是参数，会影响 kwargs 调用形式，所以最好简洁明了。

2017-02-19 13:28 UTC, Jay54520 commented on wechatpy/client/api/jsapi.py
> +    def get_jsapi_card_params(self, jsapi_card_ticket, card_type, **kwargs):
改了

2017-02-19 13:29 UTC, messense commented
感觉需要 rebase 一下，不要在 commit messages 里面增加 ci skip，会导致 CI 被忽略掉。

2017-02-19 13:30 UTC, messense commented
ci skip 应该仅仅在一些文档等修改的过程中使用，涉及到代码改动不应该使用。

2017-02-19 13:31 UTC, messense commented on wechatpy/client/api/jsapi.py
> +    def get_jsapi_card_params(self, jsapi_card_ticket, card_type, **kwargs):
并没有改对？我只的是输入参数而不是局部变量。

2017-02-19 13:35 UTC, Jay54520 commented on wechatpy/client/api/jsapi.py
> +    def get_jsapi_card_params(self, jsapi_card_ticket, card_type, **kwargs):
那我理解错了。
如果是调用，我觉得改成 card_ticket 比较好，如果是 ticket 的话怕调用者认为是 jsapi ticket

2017-02-19 13:36 UTC, messense commented on wechatpy/client/api/jsapi.py
> +    def get_jsapi_card_params(self, jsapi_card_ticket, card_type, **kwargs):
可以。

2017-02-19 13:42 UTC, Jay54520 commented
要使用 rebase 修改 git message ？我没做过

2017-02-19 13:46 UTC, messense commented
git rebase -i master

用 reword 改 commit message，然后 git push -f 提交

https://help.github.com/articles/about-git-rebase/

2017-02-19 14:19 UTC, Jay54520 commented
修改好了提交信息

2017-02-19 14:27 UTC, messense requested changes

2017-02-19 14:27 UTC, messense commented on wechatpy/client/api/jsapi.py
> +        ticket_response = self.session.get('{}_jsapi_card_ticket'.format(self.appid))
为了兼容 Python 2.6，需要写成：`'{0}_jsapi_card_ticket'.format(self.appid)`

2017-02-19 14:35 UTC, Jay54520 commented on wechatpy/client/api/jsapi.py
> +        ticket_response = self.session.get('{}_jsapi_card_ticket'.format(self.appid))
改好了。
兼容性的问题我不清楚，因为一直使用 Python3

2017-02-20 01:47 UTC, messense approved these changes

2017-02-20 01:51 UTC, messense requested changes

2017-02-20 01:51 UTC, messense commented on wechatpy/client/api/jsapi.py
> +    def get_ticket_response(self, type='jsapi'):
不要引入 breaking changes

2017-02-20 01:51 UTC, messense commented on wechatpy/client/api/jsapi.py
> +    def get_ticket_response(self, type='jsapi'):
这样可能导致用户代码挂掉。

2017-02-20 01:58 UTC, Jay54520 commented on wechatpy/client/api/jsapi.py
> +    def get_ticket_response(self, type='jsapi'):
我改一下。
因为改之前没有注意到文档是直接继承注释的

2017-02-20 02:00 UTC, messense commented on wechatpy/client/api/jsapi.py
> +    def get_ticket_response(self, type='jsapi'):
文档是 Sphinx autoclass 自动生成的。

2017-02-20 02:01 UTC, messense approved these changes

2017-02-20 02:51 UTC, merged

2017-02-20 02:52 UTC, messense commented
Thanks.