【发票】补全微信发票相关接口
wechatpy/wechatpy pull request #259
Opened 2017-07-28 15:22 UTC by LKI

close #253 
close #252 

虽然微信把这部分api放在了 `card` 下面，
但其实是相对独立的功能。
所以我们应该要新建一个新的 `invoice` API类。

2017-07-28 15:38 UTC, messense commented on wechatpy/client/api/invoice.py
> +            'seturl',
微信这 API...

2017-07-28 15:41 UTC, LKI commented on wechatpy/client/api/invoice.py
> +            'seturl',
是啊。。。我简直要看哭了。。。
而且这里的文档，还都是图，有个链接还点不进去。。。 :cry:

2017-07-28 15:42 UTC, messense requested changes
还有个 接收用户提交的抬头 的事件推送，在 wechatpy.events 里面定义

https://mp.weixin.qq.com/wiki?t=resource/res_main&id=mp1496554912_vfWU0

2017-07-28 15:42 UTC, messense commented on wechatpy/client/api/invoice.py
> +            data={
这个不太对，需要在包一层 `invoice_info`

![image](https://user-images.githubusercontent.com/1556054/28724834-fddec48c-73ed-11e7-8a21-dd64dfc4599b.png)

2017-07-28 15:46 UTC, LKI commented on wechatpy/client/api/invoice.py
> +            data={
啊，我的。我去改改

2017-07-28 15:49 UTC, LKI commented
好像漏掉了一部分API，我改一下。

2017-07-28 16:43 UTC, LKI commented
我发现漏掉的东西有点多，慢慢补，先不急着合PR。

2017-07-28 17:47 UTC, LKI commented
发票相关的文档里，应该没有遗漏的部分了。
微信的API真的丑。。。

新加了一个constants.py文件，
这样以后#260 的错误什么的也可以丢这里。

2017-07-29 01:45 UTC, messense approved these changes
LGTM

2017-07-29 01:45 UTC, merged