fixed material.update_articles, original one causes "data format error"
wechatpy/wechatpy pull request #270
Opened 2017-08-14 12:54 UTC by oldcai

https://mp.weixin.qq.com/wiki?t=resource/res_main&id=mp1444738732

2017-08-14 14:49 UTC, liriansu-opus requested changes
请删除重构导致的冗余代码哦~

2017-08-14 14:49 UTC, LKI commented on wechatpy/client/api/material.py
> +        return self.update_article(media_id, index, articles[index])
十分科学的改动，同时保持了向前兼容。
152~162行的冗余代码也请一并删掉吧，解决以后重新push就可以合进去了。

2017-08-15 01:40 UTC, messense approved these changes

2017-08-15 01:48 UTC, merged

2017-08-15 01:48 UTC, messense commented
Thanks!

2017-08-15 08:49 UTC, oldcai commented
@LKI 保留原先的接口是为了向上兼容；
如果必要可加个deprecated的warning？

2017-08-15 08:50 UTC, messense commented
@oldcai 可以加，另发 PR 吧。

2017-08-15 09:23 UTC, LKI commented
@oldcai 可以，点个赞