enterprise doc modify
wechatpy/wechatpy pull request #282
Opened 2017-08-23 06:46 UTC by zeruitle

Add 3 more supported token storage examples to enterprise，only titles， will fill details later

2017-08-23 06:48 UTC, zeruitle commented
增加了企业微信token持久化文档，只写了标题，作为测试PR，内容在之后会添加进去

2017-08-23 06:50 UTC, messense requested changes

2017-08-23 06:50 UTC, messense commented on docs/enterprise/quickstart.rst
> +wechatpy 支持多种 **AccessToken** 的持久化储存，目前支持memcached，memory，redis，shove
`memcached` 前增加一个空格。

2017-08-23 06:50 UTC, messense commented on docs/enterprise/quickstart.rst
> +Shove 示例:
这些下面增加一个空行

2017-08-24 04:57 UTC, messense approved these changes

2017-08-24 04:58 UTC, merged