增加微信代扣基础接口
wechatpy/wechatpy pull request #318
Opened 2017-12-12 10:28 UTC by noogel

2017-12-12 12:47 UTC, messense requested changes

2017-12-12 12:47 UTC, messense commented on .bumpversion.cfg
> +current_version = 1.6.0
不要手工修改版本号信息，请 revert 相关改动。

2017-12-12 12:47 UTC, messense commented on wechatpy/pay/api/withhold.py
> +        return self._get('papay/entrustweb', data=data)
应该是 query string 里面，这里应该是 `params=data`

http://docs.python-requests.org/en/master/user/quickstart/#passing-parameters-in-urls

2017-12-12 12:47 UTC, messense commented on wechatpy/pay/api/withhold.py
> +    def query_deduct(self, transaction_id=None, out_trade_no=None):
`query_order`?

2017-12-13 08:08 UTC, noogel commented on .bumpversion.cfg
> +current_version = 1.6.0
已 revert

2017-12-13 08:08 UTC, noogel commented on wechatpy/pay/api/withhold.py
> +        return self._get('papay/entrustweb', data=data)
已修改

2017-12-13 08:08 UTC, noogel commented on wechatpy/pay/api/withhold.py
> +    def query_deduct(self, transaction_id=None, out_trade_no=None):
已修改

2017-12-13 08:24 UTC, messense approved these changes

2017-12-13 08:24 UTC, merged

2017-12-13 08:24 UTC, messense commented
Thanks!