修复微信代扣接口BUG
wechatpy/wechatpy pull request #325
Opened 2018-01-10 03:44 UTC by noogel

1. 签约接口返回签约URL，并修改测试用例。
2. 接口增加 appid 和 mch_id。

2018-01-10 09:33 UTC, messense commented on wechatpy/pay/utils.py
> +def urljoin(base_url, data):
这个并没有用到吧。

2018-01-10 14:37 UTC, noogel commented on wechatpy/pay/utils.py
> +def urljoin(base_url, data):
想用来着，优化了就没用到，我删掉吧。

2018-01-11 03:55 UTC, messense requested changes

2018-01-11 03:55 UTC, messense commented on wechatpy/pay/__init__.py
> +                data.setdefault('nonce_str', random_string(32))
`setdefault` 就是做了这件事情，不需这里的判断。

2018-01-11 03:55 UTC, messense commented on wechatpy/pay/api/withhold.py
> -        return self._get('papay/entrustweb', params=data)
不需要调用这个 API 了？

2018-01-11 05:20 UTC, noogel commented on wechatpy/pay/__init__.py
> +                data.setdefault('nonce_str', random_string(32))
查询签约状态接口不能加 `nonce_str` 参数，框架中默认加的，需要参数判断是否加。 
https://pay.weixin.qq.com/wiki/doc/api/pap.php?chapter=18_2&index=4

2018-01-11 05:25 UTC, noogel commented on wechatpy/pay/__init__.py
> +                data.setdefault('nonce_str', random_string(32))
查询签约关系接口不能加 `nonce_str` 字段，需要判断是否加，就之前的框架设计没法不加这个字段请求。想通过主动设置字段为 None 来判断不添加。

2018-01-11 05:27 UTC, noogel commented on wechatpy/pay/api/withhold.py
> -        return self._get('papay/entrustweb', params=data)
接口文档没有写清楚，实际使用流程是后端SDK生成请求签约链接，交由客户端SDK去发起请求。

2018-01-11 05:29 UTC, messense commented on wechatpy/pay/__init__.py
> +                data.setdefault('nonce_str', random_string(32))
```python
In [1]: d = {'nonce_str': None}

In [2]: d.setdefault('nonce_str', 'abcd')

In [3]: d
Out[3]: {'nonce_str': None}
```

2018-01-11 08:12 UTC, noogel commented on wechatpy/pay/__init__.py
> +                data.setdefault('nonce_str', random_string(32))
理解有差异，我不希望框架 setdefault nonce_str 。

2018-01-11 08:19 UTC, messense commented on wechatpy/pay/__init__.py
> +                data.setdefault('nonce_str', random_string(32))
same effect.

2018-01-11 08:37 UTC, noogel commented on wechatpy/pay/__init__.py
> +                data.setdefault('nonce_str', random_string(32))
ok，好的~

2018-01-12 01:38 UTC, messense approved these changes

2018-01-12 01:38 UTC, merged

2018-01-12 01:38 UTC, messense commented
Thanks!