增加代扣解约接口
wechatpy/wechatpy pull request #328
Opened 2018-01-12 09:58 UTC by noogel

2018-01-12 10:00 UTC, messense commented
Please [rebase](https://www.atlassian.com/git/tutorials/rewriting-history/git-rebase).

2018-01-13 12:54 UTC, messense requested changes

2018-01-13 12:54 UTC, messense commented on wechatpy/pay/api/withhold.py
> +        if not contract_id and not(plan_id and contract_code):
```python
if not (contract_id or plan_id or contract_code):
```

2018-01-13 12:54 UTC, messense commented on wechatpy/pay/api/withhold.py
> +        申请解约
增加以下微信文档链接。

2018-01-14 01:55 UTC, noogel commented on wechatpy/pay/api/withhold.py
> +        申请解约
加上了

2018-01-14 01:55 UTC, noogel commented on wechatpy/pay/api/withhold.py
> +        if not contract_id and not(plan_id and contract_code):
改了 `if not (contract_id or plan_id and contract_code):`

2018-01-14 08:23 UTC, messense approved these changes

2018-01-14 08:23 UTC, merged

2018-01-14 08:23 UTC, messense commented
Thanks!