新增授权成功通知和授权更新通知以及获取这两个通知的方法
wechatpy/wechatpy pull request #338
Opened 2018-02-27 13:11 UTC by hunter007

2018-02-28 01:57 UTC, messense approved these changes

2018-02-28 01:58 UTC, messense requested changes

2018-02-28 01:58 UTC, messense commented on wechatpy/component.py
> +    pre_auth_Code = StringField('PreAuthCode')
`pre_auth_code`

2018-02-28 12:52 UTC, hunter007 commented
可以返回原始xml字符串，也可以返回一个对象；返回一个对象易于理解。有些人觉得用字符串方便，有些人觉得用对象方便。

2018-02-28 13:10 UTC, 007gzs commented
我的意思是解密操作需要执行两次，而且xml里已经有type了，没必要让用户在外面在判断一次调用哪个函数吧

2018-03-28 05:28 UTC, NullYing commented
updateauthorized直接忽略掉了？

2018-10-16 22:30 UTC, closed without merging