根据微信商铺API手册V1.16新增部分方法
wechatpy/wechatpy pull request #346
Opened 2018-03-19 04:58 UTC by lanmaokafei

根据微信商铺API手册V1.16新增部分方法

2018-03-19 07:18 UTC, messense requested changes

2018-03-19 07:18 UTC, messense commented on wechatpy/client/api/merchant/__init__.py
> +        获取指定分类的所有子分类
这里需要增加一个空行，否则自动生成的文档会有问题，下同。

2018-03-19 11:47 UTC, lanmaokafei commented on wechatpy/client/api/merchant/__init__.py
> +        获取指定分类的所有子分类
OK，代码在公司，明天重新提交

2018-03-19 14:51 UTC, messense requested changes

2018-03-19 14:51 UTC, messense commented on wechatpy/client/api/merchant/__init__.py
> +    def get_category_getsub(self, cate_id):
`get_subcategories`

2018-03-19 14:51 UTC, messense commented on wechatpy/client/api/merchant/__init__.py
> +    def get_category_getsku(self, cate_id):
`get_category_sku`

2018-03-19 14:51 UTC, messense commented on wechatpy/client/api/merchant/__init__.py
> +    def get_category_getproperty(self, cate_id):
`get_category_property`

2018-03-19 14:51 UTC, messense commented on wechatpy/client/api/merchant/__init__.py
> +    def update_group_name(self, group_id, group_name):
感觉应该是 `update_group_property`? 只是目前只支持 group_name?

2018-03-19 14:51 UTC, messense commented on wechatpy/client/api/merchant/__init__.py
> +    def get_all_group(self):
`get_all_groups`

2018-03-19 14:51 UTC, messense commented on wechatpy/client/api/merchant/__init__.py
> +    def get_all_shelf(self):
`get_all_shelves`

2018-03-20 00:48 UTC, lanmaokafei commented on wechatpy/client/api/merchant/__init__.py
> +    def update_group_name(self, group_id, group_name):
这个是修改分组名，下面还有一个修改分商品

2018-03-20 00:58 UTC, lanmaokafei commented on wechatpy/client/api/merchant/__init__.py
> +    def update_group_name(self, group_id, group_name):
![tim20180320085008](https://user-images.githubusercontent.com/7875669/37629975-cb187d08-2c1c-11e8-942d-b12f64eaf5d1.jpg)

2018-03-20 04:07 UTC, messense commented on wechatpy/client/api/merchant/__init__.py
> +    def update_group_property(self, group_id, group_propertys):
`group_properties`

2018-03-20 12:20 UTC, messense commented on wechatpy/client/api/merchant/__init__.py
> +    def group_properties(self, group_id, group_propertys):
这里是要改的参数名...

```python
def update_group_property(self, group_id, properties):
    ...
```

2018-03-20 12:21 UTC, messense commented on wechatpy/client/api/merchant/__init__.py
> +    def group_products(self, group_id, product_data):
换回去。

2018-03-21 16:32 UTC, lanmaokafei commented on wechatpy/client/api/merchant/__init__.py
> +    def group_properties(self, group_id, group_propertys):
回滚了

2018-03-22 07:26 UTC, messense commented on wechatpy/client/api/merchant/__init__.py
> +    def group_properties(self, group_id, group_propertys):
这里不是没改回去？

2018-03-22 07:36 UTC, lanmaokafei commented on wechatpy/client/api/merchant/__init__.py
> +    def update_group_property(self, group_id, group_propertys):
这里和下面的冲突...

2018-03-22 07:37 UTC, messense commented on wechatpy/client/api/merchant/__init__.py
> +    def update_group_property(self, group_id, group_propertys):
group_propertys 拼写错误。

2018-03-22 07:49 UTC, lanmaokafei commented on wechatpy/client/api/merchant/__init__.py
> +    def update_group_property(self, group_id, group_propertys):
呃...没看清楚...太大意了，条件反射以为是说方法名称...

2018-03-22 07:51 UTC, lanmaokafei commented on wechatpy/client/api/merchant/__init__.py
> +    def update_group_property(self, group_id, group_propertys):
怪了，提交了还是有问题？

2018-03-22 13:04 UTC, messense approved these changes

2018-03-22 13:04 UTC, merged