add: support for transfer to bankcard
wechatpy/wechatpy pull request #350
Opened 2018-04-03 03:32 UTC by filosfino

https://pay.weixin.qq.com/wiki/doc/api/tools/mch_pay.php?chapter=24_2

2018-04-03 03:38 UTC, messense requested changes

2018-04-03 03:38 UTC, messense commented on wechatpy/pay/utils.py
> +def rsa_encrypt(data, pem):
这样会依赖于 pycrypto，不希望如此，需要同时提供基于 [cryptography](https://cryptography.io/en/latest/) 的实现。

未来可能会去除对 pycrypto 的支持。

2018-04-03 04:14 UTC, filosfino commented on wechatpy/pay/utils.py
> +def rsa_encrypt(data, pem):
好，我研究一下这个库

2018-04-03 08:26 UTC, filosfino commented
@messense 看一下这样写 ok 吗？

2018-04-03 08:50 UTC, messense requested changes

2018-04-03 08:50 UTC, messense commented on wechatpy/pay/utils.py
> +    except ModuleNotFoundError:
需要兼容 Python 3.6 以下的版本，还是用 `ImportError` 吧

2018-04-03 08:54 UTC, messense requested changes

2018-04-03 08:54 UTC, messense commented on wechatpy/pay/utils.py
> +    encoded_data = data.encode() if not isinstance(data, bytes) else data
为了兼容 Python 2 应该需要指定 utf-8 编码。

2018-04-03 08:54 UTC, messense commented on wechatpy/pay/utils.py
> +    return base64.b64encode(encrypted_data).decode()
同上， `decode` 需要指定编码。

2018-04-03 08:54 UTC, messense commented on wechatpy/pay/utils.py
> +def rsa_encrypt(data, pem):
这个函数最好能增加个简单的测试，保证在 CI 上 Python 2/3 都能够测试通过。

2018-04-03 08:55 UTC, messense commented on wechatpy/pay/__init__.py
> +    transfer_bankcard = api.WeChatTransferBankCard()
是不是也可以合并到 `transfer` 里面，API 名叫 `transfer_bankcard`?

2018-04-03 10:16 UTC, filosfino commented on wechatpy/pay/utils.py
> +def rsa_encrypt(data, pem):
要不直接移除掉 pycrypto 版本的？

2018-04-03 10:17 UTC, messense commented on wechatpy/pay/utils.py
> +def rsa_encrypt(data, pem):
可以，新功能可以逐步去掉 pycrypto.

2018-04-03 10:17 UTC, filosfino commented on wechatpy/pay/utils.py
> +def rsa_encrypt(data, pem):
移除 pycrypto 支持是出于哪方面考虑？

2018-04-03 10:19 UTC, messense commented on wechatpy/pay/utils.py
> +def rsa_encrypt(data, pem):
官方版本年久失修，只有一个活跃的 fork: https://github.com/Legrandin/pycryptodome

总的来说 cryptography 维护得更好些，完全些。

2018-04-03 10:30 UTC, filosfino commented on wechatpy/pay/utils.py
> +def rsa_encrypt(data, pem):
测试的 rsa 秘钥对放在哪个目录下好一点？test/fixture 这块没有用过，不太熟悉

2018-04-03 10:36 UTC, filosfino commented on wechatpy/pay/utils.py
> +def rsa_encrypt(data, pem):
学习了：）
之前没有参与过开源软件的开发，这方面有很多不足，还要多学习哈

2018-04-03 10:42 UTC, filosfino commented on wechatpy/pay/utils.py
> +def rsa_encrypt(data, pem):
新建了个 tests/cert 目录，放这里了

2018-04-03 11:16 UTC, messense commented on tests/test_utils.py
> +        from wechatpy.pay.utils import rsa_encrypt, rsa_decrypt
```python
try:
    from wechatpy.pay.utils import rsa_encrypt, rsa_decrypt
except ImportError:
    return
```

在没有 cryptography 的时候跳过这个测试。

2018-04-03 11:17 UTC, messense commented on wechatpy/pay/utils.py
> +from cryptography.hazmat.primitives.asymmetric import padding
把 import 放到需要用的函数里面。

2018-04-04 02:50 UTC, messense commented on wechatpy/pay/base.py
> +    def rsa_key(self):
这个是不是没有必要暴露到 WeChatPay 这层？

2018-04-04 02:50 UTC, messense commented on wechatpy/pay/api/transfer.py
> +    def get_rsa_key(self):
`get_rsa_public_key`

2018-04-04 02:54 UTC, messense commented on tests/test_utils.py
> +            from wechatpy.pay.utils import rsa_encrypt, rsa_decrypt
my bad, 这里应该改成 `import cryptography`，因为 ras_encrypt 等把 import 放到 function 里面了。

2018-04-04 02:58 UTC, messense commented on tests/test_utils.py
> +            from wechatpy.pay.utils import rsa_encrypt, rsa_decrypt
更好的办法使用 [`pytest.skipif`](https://pytest.readthedocs.io/en/reorganize-docs/new-docs/user/skipping.html)

```python
def skip_if_no_cryptography():
    try:
        import cryptography  # NOQA
        return False
    except ImportError:
        return True

class XXXTest:
    @pytest.mark.skipif(skip_if_no_cryptography(), reason = 'no cryptography')
    def test_rsa_encrypt_decrypt(self):
        ...
```

2018-04-04 04:11 UTC, messense commented on tests/skip_conditions.py
> +def skip_if_no_cryptography():
简单起见可以直接定义在 `test_utils.py` 里面，等以后有需要共用再抽出来。

2018-04-04 04:24 UTC, messense commented on wechatpy/pay/utils.py
> +    encrypted_data = encrypted_data.encode('utf-8') if not isinstance(encrypted_data, bytes) else encrypted_data
同上。

2018-04-04 04:32 UTC, messense commented on wechatpy/pay/utils.py
> +            label=b'',
`label=None` 文档说和 `b''` 等价

2018-04-04 04:33 UTC, messense commented
LGTM and feel free to merge with test passes

2018-04-04 05:25 UTC, messense commented on wechatpy/pay/utils.py
> +def rsa_encrypt(data, pem, b64_encode=True):
从文档看 base64 编码是必需的？

2018-04-04 05:47 UTC, messense approved these changes

2018-04-04 05:47 UTC, merged

2018-04-04 06:49 UTC, filosfino commented on wechatpy/pay/utils.py
> +def rsa_encrypt(data, pem, b64_encode=True):
是必须的，加这个参数方便 test 中的 decrypt，不用重新 b64decode 了。decrypt 函数在接口中也用不到，也是为了 test 写的