尽量使代码符合PEP8规范
wechatpy/wechatpy pull request #358
Opened 2018-05-17 09:27 UTC by csrftoken

`getattr` to `hasattr`

2018-05-17 09:33 UTC, liriansu-opus requested changes

2018-05-17 09:33 UTC, LKI commented on wechatpy/client/api/base.py
> +        if hasattr(self, 'API_BASE_URL'):
在 https://github.com/jxtech/wechatpy/blob/master/wechatpy/client/base.py#L29 这里会初始化一个空的 `API_BASE_URL`

所以得用 `hasattr` 加取值判断，这样判断可能会凉

2018-05-17 09:46 UTC, csrftoken commented on wechatpy/client/api/base.py
> +        if hasattr(self, 'API_BASE_URL'):
那如果 getattr(self, 'API_BASE_URL')   获取到的是 初始化的 API_BASE_URL， 那下面那句不执行那
kwargs['api_base_url'] = self.API_BASE_URL

2018-05-17 09:53 UTC, LKI commented on wechatpy/client/api/base.py
> +        if hasattr(self, 'API_BASE_URL'):
对~ 如果获取到是初始化的~ 下面的是不执行的~

2018-06-07 17:27 UTC, ldsink commented
所以可以关闭这个PR了？

2018-06-08 03:56 UTC, closed without merging