小程序数据签名校验
wechatpy/wechatpy pull request #449
Opened 2019-04-29 03:13 UTC by Xavier-Lam

2019-04-29 10:12 UTC, ldsink commented on wechatpy/utils.py
> +    return json.loads(raw_data)
这个返回没什么意义，而且和上面的 check_signature 不一致了。
看名字都是检查签名，但是一个返回，一个不返回。
建议去掉。

2019-04-29 10:12 UTC, ldsink commented on tests/test_utils.py
> +        self.assertEqual(data, checked_data)
data 是 json.loads(raw_data)，check_wxa_signature 返回值也是  json.loads(raw_data)。并没有对这个做修改，这个比较无意义。

建议和 check_signature 保持一致。

2019-04-30 03:53 UTC, Xavier-Lam commented on wechatpy/utils.py
> +    return json.loads(raw_data)
调用这个函数的场景是 前端拿到rawData字符串和signature 传给后端使用时 后端校验签名一致 则信任rawData数据 并对rawData进行进一步处理
需要进一步处理rawData 就需要进行json.loads 如果这个函数只检查签名是否正确 不进行json.loads 则在检查签名正确后 用户还需再次自行执行json.loads 遂将这个操作封装于函数内

2019-05-05 09:10 UTC, messense commented on wechatpy/utils.py
> +    return json.loads(raw_data)
从语义而言应该这里的 `json.loads`，交给用户处理并不是很复杂。

2019-05-05 09:12 UTC, messense requested changes

2019-05-05 09:12 UTC, messense commented on wechatpy/utils.py
> +        from wechatpy.exceptions import InvalidSignatureException
可以把这个 import 提到 top level 并删除上面 `check_signature` 函数体中相同的 import

2019-05-05 09:12 UTC, messense commented on tests/test_utils.py
> +    def test_check_wxa_signature(self):
增加一个带中文字符的测试用例。

2019-05-08 05:52 UTC, Xavier-Lam commented on wechatpy/utils.py
> +    return json.loads(raw_data)
我这几天改一下

2019-05-13 10:14 UTC, Xavier-Lam commented on tests/test_utils.py
> +    def test_check_wxa_signature(self):
增加了一个中文测试用例

2019-05-13 10:14 UTC, Xavier-Lam commented on wechatpy/utils.py
> +    return json.loads(raw_data)
已移除

2019-05-13 10:15 UTC, Xavier-Lam commented on wechatpy/utils.py
> +        from wechatpy.exceptions import InvalidSignatureException
移到top level会造成循环引用 就没有提出来了

2019-05-13 10:16 UTC, Xavier-Lam commented
我修改pull request的时候 是不是不应该rebase上游主分支...

2019-05-14 01:59 UTC, messense approved these changes

2019-05-14 02:00 UTC, merged

2019-05-14 02:00 UTC, messense commented
Thanks!