增加获取小程序模板库API
wechatpy/wechatpy pull request #466
Opened 2019-06-24 07:54 UTC by atanx

小程序第三方平台，增加获取小程序模板库API

2019-06-24 07:57 UTC, atanx commented
小程序第三方平台，增加获取小程序模板库API接口 get_template_list

2019-06-24 10:10 UTC, liriansu-opus requested changes
对应方法请加到 [wechatpy/client/api/wxa.py](https://github.com/jxtech/wechatpy/blob/master/wechatpy/client/api/wxa.py) 这个文件里

2019-06-24 10:11 UTC, LKI commented on wechatpy/component.py
> +         https://api.weixin.qq.com/wxa/gettemplatelist?access_token=TOKEN
文档地址应当改为
`https://developers.weixin.qq.com/miniprogram/dev/api-backend/open-api/template-message/templateMessage.getTemplateList.html`

2019-06-24 10:12 UTC, LKI commented on wechatpy/component.py
> +            {
这个不是一个合法的 JSON 格式，可以参考官方的返回示例

```
{
  "errcode": 0,
  "errmsg": "ok",
  "list": [
    {
      "template_id": "wDYzYZVxobJivW9oMpSCpuvACOfJXQIoKUm0PY397Tc",
      "title": "购买成功通知",
      "content": "购买地点{{keyword1.DATA}}\n购买时间{{keyword2.DATA}}\n物品名称{{keyword3.DATA}}\n",
      "example": "购买地点：TIT造舰厂\n购买时间：2016年6月6日\n物品名称：咖啡\n"
    }
  ]
}
```

2019-06-24 10:12 UTC, LKI commented on wechatpy/component.py
> +    def get_template_list(self):
方法上需要提供分页的参数

2019-06-24 11:04 UTC, atanx commented on wechatpy/component.py
> +    def get_template_list(self):
不是你理解的这个API, 增加的是小程序第三方平台代码模板库。
文档见接口5：https://open.weixin.qq.com/cgi-bin/showdocument?action=dir_list&t=resource/res_list&verify=1&id=open1506504150_nMMh6&token=&lang=zh_CN

2019-06-24 11:05 UTC, atanx commented on wechatpy/component.py
> +            {
返回的结果是json类型，这个返回示例少了双引号（拷贝官方文档的，需要修正）。

2019-06-24 11:12 UTC, atanx commented
这个方法最好是放在component.py中，原因有二：
1. 小程序代码模板库归平台所有，而非授权的小程序，逻辑上只跟平台相关。
2. 该接口需要使用平台的access_token,而非小程序授权的access_token。

2019-06-24 12:34 UTC, ldsink commented on wechatpy/component.py
> +    def get_template_list(self):
函数名为 get_wxa_template_list 是否更好？

get_template_list 太大了，也不明确。

2019-06-24 12:34 UTC, ldsink commented on wechatpy/component.py
> +    def delete_template(self, template_id):
建议全部小程序模板相关的接口函数里面带上 wxa_ 体现这一点。

2019-06-25 05:57 UTC, atanx commented on wechatpy/component.py
> +    def delete_template(self, template_id):
可以， 否则容易跟wxa.py中模板消息方法搞混。

2019-06-25 08:20 UTC, atanx commented on wechatpy/component.py
> +    def get_template_list(self):
已调整。

2019-06-25 08:39 UTC, atanx commented
> 对应方法请加到 [wechatpy/client/api/wxa.py](https://github.com/jxtech/wechatpy/blob/master/wechatpy/client/api/wxa.py) 这个文件里

@LKI 不认为需要放在 [wechatpy/client/api/wxa.py](https://github.com/jxtech/wechatpy/blob/master/wechatpy/client/api/wxa.py)  补充的方法是第三方平台专有，与普通小程序的那些接口无关。使用的access_token也是第三方平台的component_access_token。

2019-06-26 06:51 UTC, atanx commented on wechatpy/component.py
> +    def get_template_list(self):
@ldsink 能merge进去吗？

2019-06-26 07:20 UTC, ldsink commented
我觉得函数位置应该在 wxa 下面。理由：

1. component 是基础第三方/平台相关的基础库，应该用于处理微信这套消息验证、授权逻辑。**不应该在这个下面实现具体功能的API**，具体的功能的API在 `client/api/` 下面
1. 即使是第三方平台专有的接口，也应该放在 wxa 这个具体的 API 接口下面，通过名称标明。（这会导致自己管理的小程序调用这个接口失败，但是这是开发者的函数调用错误。wechatpy 这个库的接口设计是一致的。）
1. 应该优先保证 wechatpy 项目结构，去放到合适的位置，并实现接口。而不是根据微信调用传递什么参数决定接口放什么位置。

2019-06-26 08:59 UTC, atanx commented
> 我觉得函数位置应该在 wxa 下面。理由：
> 
> 1. component 是基础第三方/平台相关的基础库，应该用于处理微信这套消息验证、授权逻辑。**不应该在这个下面实现具体功能的API**，具体的功能的API在 `client/api/` 下面
> 2. 即使是第三方平台专有的接口，也应该放在 wxa 这个具体的 API 接口下面，通过名称标明。（这会导致自己管理的小程序调用这个接口失败，但是这是开发者的函数调用错误。wechatpy 这个库的接口设计是一致的。）
> 3. 应该优先保证 wechatpy 项目结构，去放到合适的位置，并实现接口。而不是根据微信调用传递什么参数决定接口放什么位置。

同意优先保证现有wechatpy项目结构。最开始我也是考虑放在`client/api/wxa.py`中，后来实施过程中基于
一下两点改放在了`component.py`里。
1. component的专有接口不依赖client，当尚未有小程序授权给平台时，无法创建client，进而也不能调用到这些接口, 而现有框架要调用`client/api/wxa.py`中的方法就必须实例化出一个client
2. wxa.py中目前所有的方法默认传递小程序的accss_token，而平台专有接口需要component_access_token，强行放入导致对现有框架的破坏（access_token已经封装在client._request方法中了）。

 你们觉得如果放在`client/api/wxa.py`，在不增加太多对框架的改动以及用户的理解成本，应当怎么解决上述两个问题？

2019-07-20 03:13 UTC, closed without merging