新增批量添加卡券接口
wechatpy/wechatpy pull request #556
Opened 2020-04-07 05:07 UTC by myuanz

我在新增卡券的时候发现了`get_jsapi_card_params`, 但是它生成的并不能用, 于是我新创建了另一个函数`get_jsapi_add_card_params`用于生成新增卡券时的参数.

全部所做有:  
- 引入了一个新的包
- 添加了 card_ext 的结构定义
- 新增了 card_ext 生成函数.

2020-04-07 05:27 UTC, liriansu-opus requested changes
也请在 `test/test_client.py` 里补一下对应的单元测试吧，感谢

2020-04-07 05:27 UTC, LKI commented on wechatpy/client/api/jsapi.py
> +        获取 api_ticket：是用于调用微信卡券JS API的临时票据, 有效期为7200 秒, 通过access_token 来获取.
根据[中文排版指北](https://github.com/sparanoid/chinese-copywriting-guidelines/blob/master/README.zh-CN.md)，中文之间的符号应当是使用全角符号的

（一个小建议，不过因为项目里 comment 风格不一，这点可以不改）

2020-04-07 05:27 UTC, LKI commented on wechatpy/client/api/jsapi.py
> +        card_ext = JsapiCardExt(
这里直接返回 `dict` 类型吧，因为全项目风格都是使用基本类型 (`dict`, `list`) 作为参数与返回值类型的。

这样也可以去掉 `pydantic` 这个依赖项。

2020-04-07 05:27 UTC, LKI commented on wechatpy/client/api/jsapi.py
> +        noncestr: str = "",
```suggestion
        nonce_str: str = "",
```

2020-04-07 05:36 UTC, messense commented
反正在做 breaking changes，如果 `get_jsapi_card_params` 现在是完全不能正常工作的，可以直接修复它不用添加新的方法？

2020-04-07 05:45 UTC, myuanz commented on wechatpy/client/api/jsapi.py
> +        card_ext = JsapiCardExt(
其实我原想慢慢把结构都替换一遍的, 因为之前开发的时候, 经常发生我知道微信需要这个, 但是我不知道这个字段`wechatpy`到底有没有, 怎么给的, 或者如果返回出去, 它到底什么样子. 

经常要下个断点来看到底有什么, 感觉挺痛苦的, 所以想要加一下结构定义, 开发时候有自动提示会舒服很多, 之前想要`@dataclasses`来标定, 但是它是3.7才有的功能, 就用了`pydantic`这个校验库了, 没想到它不支持3.5...

2020-04-07 05:48 UTC, myuanz commented
> 反正在做 breaking changes，如果 `get_jsapi_card_params` 现在是完全不能正常工作的，可以直接修复它不用添加新的方法？

我其实并不太明白`get_jsapi_card_params`是用来干嘛的, 感觉可能会有人使用, 所以新增了一个

2020-04-07 05:57 UTC, myuanz commented
> 也请在 `test/test_client.py` 里补一下对应的单元测试吧，感谢

下午我补上

2020-04-07 06:01 UTC, LKI commented on wechatpy/client/api/jsapi.py
> +        card_ext = JsapiCardExt(
嗯，要不这个 PR 就单纯实现功能；
假如要引入依赖替换结构的话，我觉得可以单独开个 Issue 来处理…

（多版本兼容情况下的结构的确是个头大的问题）

2020-04-07 06:02 UTC, messense commented on wechatpy/client/api/jsapi.py
> +        card_ext = JsapiCardExt(
增加 schema 是可以考虑的功能，先提个 issue 吧。

2020-04-07 06:17 UTC, myuanz commented on wechatpy/client/api/jsapi.py
> +        card_ext = JsapiCardExt(
行, 那我再改改, 不过是新开一个 PR 好呢还是就在这个 PR 里修改?  

schema 的话, 我简单仿照`@dataclasses`造一个轮子吧, 只实现基础功能也不是很复杂.

2020-04-07 06:34 UTC, messense commented on wechatpy/client/api/jsapi.py
> +        card_ext = JsapiCardExt(
直接在此修改就行了。

2020-04-07 11:51 UTC, myuanz commented on wechatpy/client/api/jsapi.py
> +        card_ext = JsapiCardExt(
我改好了, 同时也做了线上测试, 来看看吧

2020-04-08 05:13 UTC, messense commented on wechatpy/client/api/jsapi.py
> +        card_ticket: str = "",
先把类型标注去掉吧，3.5 不支持这种写法。

2020-04-08 08:16 UTC, myuanz commented on wechatpy/client/api/jsapi.py
> +        card_ticket: str = "",
OK了, 我第一次用rebase, 应该没错吧

2020-04-08 09:17 UTC, liriansu-opus reviewed
rebase 的不太对，掺杂了一些有冲突的文件。

建议 reset 以后摘掉相关文件，比如：

```bash
git reset --soft 2e4619d  # 放弃 commit 历史只保留文件
git checkout HEAD -- .github/workflows/CI.yml docs/install.rst poetry.lock pyproject.toml  # 这些文件 master 上有改动，feature branch 应该不用改
git add . && git commit -m "blablabla"  # 提交改动
git fetch origin && git rebase origin/master  # rebase master
git push -f  # force push
```

> 上面只是一些命令的样例，不保证 work :)
> 想解决的是目前 PR 中有一些混进来的 changes

2020-04-08 09:28 UTC, liriansu-opus requested changes
~~不小心~~又提了一些 comment，烦请改一下，辛苦了

2020-04-08 09:28 UTC, LKI commented on tests/test_client.py
> +        assert "outer_str" not in card_ext.dict()
一般来说单元测试中我们会用 `TestCase.assert` 系列方法，
类似的阐述在 StackOverflow 上有: https://stackoverflow.com/questions/6361147/why-do-assertions-in-unittest-use-testcase-assertequal-not-the-assert-keyword

```suggestion
        self.assertNotIn("outer_str", card_ext.dict())
```

2020-04-08 09:28 UTC, LKI commented on tests/test_client.py
> +        self.assertEqual(
```suggestion
        self.assertDictEqual(
```

2020-04-08 09:28 UTC, LKI commented on wechatpy/schemes.py
> +from typing import Text, Any
一个提示，Python 的 import 顺序是有最佳实践的，遵循标准库、三方库、项目依赖的顺序。

上述经过排序后是这样：

```python3
import warnings
from json import dumps
from time import time
from typing import Any Text

from wechatpy.utils import random_string
```

更详细的阐述在：https://www.python.org/dev/peps/pep-0008/#imports

（不过鉴于项目中我们没在 CI 检查 import order，这个也只是个小建议，不改也行）

2020-04-08 09:28 UTC, LKI commented on wechatpy/work/client/api/user.py
> +        **kwargs,
这个 changes 应该也是 master 上的，rebase 后应该会消失

2020-04-08 10:59 UTC, myuanz commented on tests/test_client.py
> +        assert "outer_str" not in card_ext.dict()
好的, 我以前用[pytest](https://docs.pytest.org/en/latest/), 文档里给的示例是`assert`, 我以为unittest也是这样的

2020-04-08 11:00 UTC, messense commented on tests/test_client.py
> +        assert "outer_str" not in card_ext.dict()
pytest 用 assert 没关系的，我们这里 unittest 也是用 pytest 跑的，可以不用改。

2020-04-08 11:00 UTC, myuanz commented on wechatpy/schemes.py
> +from typing import Text, Any
谢谢提醒, 待会改

2020-04-08 11:25 UTC, myuanz commented on wechatpy/work/client/api/user.py
> +        **kwargs,
我 reset 之后的提交在 rebase 之后消失了, 顺便这个逗号依然存在🤔, 真叫人揪心

2020-04-08 11:27 UTC, myuanz commented on wechatpy/work/client/api/user.py
> +        **kwargs,
不过人生中第一次给大项目的 PR 应该快好了 2333

2020-04-09 02:06 UTC, merged

2020-04-09 02:07 UTC, LKI commented
Congratulations 🌹