完善企业微信标签的接口
wechatpy/wechatpy pull request #581
Opened 2020-05-05 14:09 UTC by huimingz

标签的用户删除和添加接口添加部门参数(#517)，添加接口文档和类型注解，参数检查。

2020-05-05 15:43 UTC, liriansu-opus requested changes

2020-05-05 15:43 UTC, LKI commented on wechatpy/work/client/api/tag.py
> +        self, tag_id: int, user_ids: Optional[List[str]] = None, dept_ids: Optional[List[int]] = None
```suggestion
        self, tag_id: int, user_ids: Optional[List[str]] = None, department_ids: Optional[List[int]] = None
```

要不还是用全称？

2020-05-05 15:43 UTC, LKI commented on wechatpy/work/client/api/tag.py
> +        self, tag_id: int, user_ids: Optional[List[str]] = None, dept_ids: Optional[List[int]] = None
```suggestion
        self, tag_id: int, user_ids: Optional[List[str]] = None, department_ids: Optional[List[int]] = None
```

2020-05-05 15:57 UTC, huimingz commented on wechatpy/work/client/api/tag.py
> +        self, tag_id: int, user_ids: Optional[List[str]] = None, dept_ids: Optional[List[int]] = None
可以的

2020-05-05 16:08 UTC, huimingz commented on wechatpy/work/client/api/tag.py
> +        self, tag_id: int, user_ids: Optional[List[str]] = None, dept_ids: Optional[List[int]] = None
因为还有单元测试的部分需要更改，直接重写提交一次比较方便

2020-05-06 02:07 UTC, LKI commented
LGTM, 超棒！

2020-05-06 02:08 UTC, merged

2020-05-06 02:19 UTC, messense commented
@huimingz Thank you for your contribution. I've invited you to be a member of the `wechatpy` organization.