简化事件注册
wechatpy/wechatpy pull request #706
Opened 2022-03-16 15:27 UTC by yqkcn

2022-03-16 15:46 UTC, yqkcn commented
这样写会把微信和企业微信的事件弄混，我再改一下

2022-03-17 02:02 UTC, LKI requested changes
这个要不加两个简单的 unittest 吧

2022-03-17 06:05 UTC, messense approved these changes
💯

2022-03-17 09:30 UTC, LKI commented
lgtm

2022-03-17 09:31 UTC, merged